name: Déploiement du site Le Souffleur de Verre
on:
  push:
    branches: [ "test" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v4

    - name: Vérification du contenu du dépôt
      run: ls -l
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'  # Remplacez par la version de Node.js que vous souhaitez utiliser
        cache: 'npm'

    - name: Installation des dépendances et démarrage de l'application
      working-directory: ./frontend
      run: |
        npm install
        npm start