name: Déploiement du site Le Souffleur de Verre
on:
  push:
    branches: [ "test" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du dépôt et installation des dépendances
      uses: actions/checkout@v4
      with:
        path: frontend  # Spécifiez le chemin où vous souhaitez effectuer le checkout

    - name: Setup Node.js et démarrage de l'application
      working-directory: ../frontend
      run: |
        npm install
        npm start