name: Déploiement du site Le Souffleur de Verre
on:
  push:
    branches: [ "test" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
    - run: cd frontend
    - run: npm start
