name: Déploiement du site Le Souffleur de Verre
on:
  push:
    branches: [ "test" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v4

    - name: Installation et démarrage de npm dans le dossier frontend
      run: |
        cd frontend
        npm install
        npm start
      working-directory: ./frontend
      shell: bash
